version: 2
updates:
  ### update dependencies daily
  - package-ecosystem: 'nuget'
    directory: '/'
    # monthly at 5am UTC
    schedule:
      interval: 'monthly'
    # set reviewers
    reviewers:
      - 'kbrashears5'