name: Auto Create Collabs

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  collabs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Auto Create Collabs
        uses: kbrashears5/github-action-auto-create-collabs@master
        with:
          REPOSITORIES: 'ALL'
          USERS: |
            github-action-bot
          TOKEN: ${{ secrets.ACTIONS }}