name: Typescript File Sync

on:
  push:
    branches:
      - main

jobs:
  file_syncs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v3
      # all
      - name: All
        uses: kbrashears5/github-action-file-sync@v3
        with:
          REPOSITORIES: |
            kbrashears5/homebridge-schedule
            kbrashears5/typescript-aws-apigateway-helper
            kbrashears5/typescript-aws-cloudwatch-helper
            kbrashears5/typescript-aws-dynamo-helper
            kbrashears5/typescript-aws-helpers
            kbrashears5/typescript-aws-kms-helper
            kbrashears5/typescript-aws-lambda-helper
            kbrashears5/typescript-aws-s3-helper
            kbrashears5/typescript-aws-ses-helper
            kbrashears5/typescript-aws-sns-helper
            kbrashears5/typescript-aws-sqs-helper
            kbrashears5/typescript-aws-ssm-helper
            kbrashears5/typescript-aws-sts-helper
            kbrashears5/typescript-cache-helper
            kbrashears5/typescript-helper-functions
            kbrashears5/typescript-ilogger
          FILES: |
            .github/workflows/issue-assigner.yml=.github/workflows/issue-assigner.yml
            LICENSE
            typescript/.eslintignore
            typescript/.eslintrc.yml
            typescript/.gitignore
            typescript/.npmrc
            typescript/.prettierignore
            typescript/.prettierrc.yml
            typescript/ci-cd.yml=.github/workflows/ci-cd.yml
            typescript/codeql-analysis.yml=.github/workflows/codeql-analysis.yml
            typescript/dependabot.yml=.github/dependabot.yml
            typescript/pre-commit=.githooks/pre-commit
            typescript/sync-github-with-package-json.yml=.github/workflows/sync-github-with-package-json.yml
            typescript/tsconfig.eslint.json
          TOKEN: ${{ secrets.ACTIONS }}
      # tsconfig - lib
      - name: tsconfig - lib
        uses: kbrashears5/github-action-file-sync@v3
        with:
          REPOSITORIES: |
            kbrashears5/typescript-aws-apigateway-helper
            kbrashears5/typescript-aws-cloudwatch-helper
            kbrashears5/typescript-aws-dynamo-helper
            kbrashears5/typescript-aws-helpers
            kbrashears5/typescript-aws-kms-helper
            kbrashears5/typescript-aws-lambda-helper
            kbrashears5/typescript-aws-s3-helper
            kbrashears5/typescript-aws-ses-helper
            kbrashears5/typescript-aws-sns-helper
            kbrashears5/typescript-aws-sqs-helper
            kbrashears5/typescript-aws-ssm-helper
            kbrashears5/typescript-aws-sts-helper
            kbrashears5/typescript-cache-helper
            kbrashears5/typescript-helper-functions
            kbrashears5/typescript-ilogger
          FILES: |
            typescript/tsconfig-lib.json=tsconfig.json
          TOKEN: ${{ secrets.ACTIONS }}
      # tsconfig - dist
      - name: tsconfig - dist
        uses: kbrashears5/github-action-file-sync@v3
        with:
          REPOSITORIES: |
            kbrashears5/homebridge-schedule
          FILES: |
            typescript/tsconfig-dist.json=tsconfig.json
          TOKEN: ${{ secrets.ACTIONS }}
