name: Net Standard File Sync

on:
  push:
    branches:
      - main

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v4
      # regular files
      - name: Files
        uses: kbrashears5/github-action-file-sync@v3.0.0
        with:
          REPOSITORIES: |
            kbrashears5/net-standard-aws-s3-helper
            kbrashears5/net-standard-aws-sqs-helper
            kbrashears5/net-standard-cache-helper
            kbrashears5/net-standard-http-helper
            kbrashears5/net-standard-logger
            kbrashears5/net-standard-opc-ua-helper
            kbrashears5/net-standard-test-helper
          FILES: |
            .github/workflows/issue-assigner.yml=.github/workflows/issue-assigner.yml
            LICENSE
            net-standard/.editorconfig=.editorconfig
            net-standard/.gitignore=.gitignore
            net-standard/codeql-analysis.yml=.github/workflows/codeql-analysis.yml
            net-standard/dependabot.yml=.github/dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}