name: Shell File Sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      # regular files
      - name: Files
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            kbrashears5/github-action-file-sync
            kbrashears5/github-action-repo-sync
            kbrashears5/github-action-repo-settings-sync
            kbrashears5/github-action-release-maker
            kbrashears5/github-action-issue-assigner
            kbrashears5/github-action-auto-accept-collabs
            kbrashears5/github-action-auto-create-collabs
          FILES: |
            LICENSE
            shell/azure-pipelines.yml
            release-maker.yml=.github/workflows/release-maker.yml
            .github/workflows/issue-assigner.yml=.github/workflows/issue-assigner.yml
            .github/workflows/stale-issues.yml=.github/workflows/stale-issues.yml
            shell/sync-github-with-metadata-json.yml=.github/workflows/sync-github-with-metadata-json.yml
          TOKEN: ${{ secrets.ACTIONS }}