name: Shell File Sync

on:
  push:
    branches:
      - main

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v3
      # regular files
      - name: Files
        uses: kbrashears5/github-action-file-sync@v3.0.0
        with:
          REPOSITORIES: |
            kbrashears5/github-action-auto-accept-collabs
            kbrashears5/github-action-auto-create-collabs
            kbrashears5/github-action-file-sync
            kbrashears5/github-action-issue-assigner
            kbrashears5/github-action-release-maker
            kbrashears5/github-action-repo-settings-sync
            kbrashears5/github-action-repo-sync
          FILES: |
            .github/workflows/issue-assigner.yml=.github/workflows/issue-assigner.yml
            LICENSE
            shell/dependabot.yml=.github/dependabot.yml
            shell/repo-sync.yml=.github/workflows/repo-sync.yml
          TOKEN: ${{ secrets.ACTIONS }}
