name: Python File Sync

on:
  push:
    branches:
      - main

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v4
      - name: Files
        uses: kbrashears5/github-action-file-sync@v3.0.0
        with:
          REPOSITORIES: |
            kbrashears5/github-secret-recycler
          FILES: |
            .github/workflows/issue-assigner.yml=.github/workflows/issue-assigner.yml
            LICENSE
            python/dependabot.yml=.github/dependabot.yml
            python/repo-metadata-sync.yml=.github/workflows/repo-metadata-sync.yml
          TOKEN: ${{ secrets.ACTIONS }}