name: Shell File Sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  file_syncs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      # azure pipelines
      - name: Azure Pipelines
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            kbrashears5/github-action-file-sync
            kbrashears5/github-action-repo-sync
            kbrashears5/github-action-repo-settings-sync
            kbrashears5/github-action-release-maker
          FILES: |
            release-maker.yml=.github/workflows/release-maker.yml
            shell/azure-pipelines.yml
          TOKEN: ${{ secrets.ACTIONS }}