name: Typescript File Sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  file_syncs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      # all
      - name: All
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            kbrashears5/homebridge-schedule
            kbrashears5/typescript-helper-functions
            kbrashears5/typescript-cache-helper
            kbrashears5/typescript-ilogger
            kbrashears5/typescript-aws-helpers
            kbrashears5/typescript-aws-apigateway-helper
            kbrashears5/typescript-aws-cloudwatch-helper
            kbrashears5/typescript-aws-dynamo-helper
            kbrashears5/typescript-aws-kms-helper
            kbrashears5/typescript-aws-lambda-helper
            kbrashears5/typescript-aws-s3-helper
            kbrashears5/typescript-aws-ses-helper
            kbrashears5/typescript-aws-sns-helper
            kbrashears5/typescript-aws-sqs-helper
            kbrashears5/typescript-aws-ssm-helper
            kbrashears5/typescript-aws-sts-helper
          FILES: |
            typescript/.npmrc
            typescript/.gitignore
            typescript/LICENSE
            typescript/tslint.json
            typescript/dependabot.yml=.github/dependabot.yml
            release-maker.yml=.github/workflows/release-maker.yml
            .github/workflows/issue-assigner.yml=.github/workflows/issue-assigner.yml
            typescript/sync-github-with-package-json.yml=.github/workflows/sync-github-with-package-json.yml
            typescript/codeql-analysis.yml=.github/workflows/codeql-analysis.yml
          TOKEN: ${{ secrets.ACTIONS }}
      # tsconfig - lib
      - name: tsconfig - lib
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            kbrashears5/typescript-helper-functions
            kbrashears5/typescript-cache-helper
            kbrashears5/typescript-ilogger
            kbrashears5/typescript-aws-helpers
            kbrashears5/typescript-aws-apigateway-helper
            kbrashears5/typescript-aws-cloudwatch-helper
            kbrashears5/typescript-aws-dynamo-helper
            kbrashears5/typescript-aws-kms-helper
            kbrashears5/typescript-aws-lambda-helper
            kbrashears5/typescript-aws-s3-helper
            kbrashears5/typescript-aws-ses-helper
            kbrashears5/typescript-aws-sns-helper
            kbrashears5/typescript-aws-sqs-helper
            kbrashears5/typescript-aws-ssm-helper
            kbrashears5/typescript-aws-sts-helper
          FILES: |
            typescript/tsconfig-lib.json=tsconfig.json
          TOKEN: ${{ secrets.ACTIONS }}
      # tsconfig - dist
      - name: tsconfig - dist
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            kbrashears5/homebridge-schedule
          FILES: |
            typescript/tsconfig-dist.json=tsconfig.json
          TOKEN: ${{ secrets.ACTIONS }}
      # azure pipelines no tests
      - name: Azure Pipelines No Tests
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            kbrashears5/typescript-ilogger
            kbrashears5/homebridge-schedule
          FILES: |
            typescript/azure-pipelines.yml
          TOKEN: ${{ secrets.ACTIONS }}
      # azure pipelines with tests
      - name: Azure Pipelines With Tests
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            kbrashears5/typescript-helper-functions
            kbrashears5/typescript-cache-helper
            kbrashears5/typescript-aws-apigateway-helper
            kbrashears5/typescript-aws-cloudwatch-helper
            kbrashears5/typescript-aws-dynamo-helper
            kbrashears5/typescript-aws-kms-helper
            kbrashears5/typescript-aws-lambda-helper
            kbrashears5/typescript-aws-s3-helper
            kbrashears5/typescript-aws-ses-helper
            kbrashears5/typescript-aws-sns-helper
            kbrashears5/typescript-aws-sqs-helper
            kbrashears5/typescript-aws-ssm-helper
            kbrashears5/typescript-aws-sts-helper
          FILES: |
            typescript/azure-pipelines-tests.yml=azure-pipelines.yml
          TOKEN: ${{ secrets.ACTIONS }}
      # azure pipelines v2 no tests
      - name: Azure Pipelines With Tests
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            kbrashears5/typescript-aws-helpers
          FILES: |
            typescript/azure-pipelines-v2.yml=azure-pipelines.yml
          TOKEN: ${{ secrets.ACTIONS }}
