name: Repo Metadata Sync (this repo)

on:
  push:
    branches:
      - master

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Repo Sync
        uses: kbrashears5/github-action-repo-sync@v1
        with:
          TYPE: npm
          PATH: metadata.json
          TOKEN: ${{ secrets.ACTIONS }}