name: Repo Settings Sync

on:
  push:
    branches:
      - main

jobs:
  repo_settings_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Setup
        uses: kbrashears5/github-action-repo-settings-sync@v2
        with:
          ALLOW_PROJECTS: 'false'
          ALLOW_WIKI: 'false'
          SQUASH_MERGE: 'true'
          MERGE_COMMIT: 'false'
          REBASE_MERGE: 'false'
          DELETE_HEAD: 'true'
          TOKEN: ${{ secrets.ACTIONS }}